services:
  wywywebsite-cache_create_tables:
    container_name: wywywebsite-cache_create_tables
    tty: true
    working_dir: /apps/create_tables
    build:
      context: ../
      dockerfile: apps/create_tables/Dockerfile
      args:
        CONFIG_PATH: ${UNIVERSAL_CONFIG_DIR}/config.yml
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env.dev
        required: true
    environment:
      DATABASE_PORT: 5432
    develop:
      watch:
        - action: sync+restart
          path: ./../apps/create_tables
          target: ./apps/create_tables
          initial_sync: true
    depends_on:
      wywywebsite-cache_database:
        condition: service_healthy
    volumes:
      - ${UNIVERSAL_CONFIG_DIR}/config.yml:/apps/create_tables/config.yml
    command: python3 create_tables.py

  wywywebsite-cache_sync:
    container_name: wywywebsite-cache_sync
    tty: true
    working_dir: /apps/sync
    build:
      context: ../
      dockerfile: apps/sync/Dockerfile
      args:
        CONFIG_PATH: ${UNIVERSAL_CONFIG_DIR}/config.yml
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env.dev
        required: true
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PORT=5432
      - DEV=TRUE
    secrets:
      - admin
    ports:
      - 8000:8000
    volumes:
      - ./../apps/sync:/apps/sync
      - ${UNIVERSAL_CONFIG_DIR}/config.yml:/apps/sync/config.yml
    depends_on:
      wywywebsite-cache_database:
        condition: service_healthy

  # @TODO secrets for db authentication
  wywywebsite-cache_database:
    container_name: wywywebsite-cache_postgres
    build:
      context: ../
      dockerfile: apps/postgres/Dockerfile
    restart: always
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/cache/.env.dev
        required: true
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}"]
      interval: 5m
      timeout: 5s
      start_period: 3s
      retries: 10
    volumes:
      - ${DATA_DIR}/cache/postgres:/var/lib/postgresql/data
    shm_size: 128mb

secrets:
  admin:
    file: ${SECRETS_DIR}/admin.txt
