services:
  wywywebsite-cache_create_tables:
    container_name: wywywebsite-cache_create_tables
    tty: true
    working_dir: /apps/create_tables
    build:
      context: ../
      dockerfile: apps/create_tables/Dockerfile
      args:
        CONFIG_PATH: ./../../config.yml
    env_file:
      - path: .env
        required: true
      - path: .env.dev
        required: true
    develop:
      watch:
        - action: sync+restart
          path: ./../apps/create_tables
          target: ./apps/create_tables
          initial_sync: true
    depends_on:
      wywywebsite-cache_database:
        condition: service_healthy
    command: python3 create_tables.py

  wywywebsite-cache_sync:
    container_name: wywywebsite-cache_sync
    tty: true
    working_dir: /apps/sync
    build:
      context: ../
      dockerfile: apps/sync/Dockerfile
    env_file:
      - path: .env
        required: true
      - path: .env.dev
        required: true
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PORT=${DATABASE_PORT}
      - DEV=TRUE
    secrets:
      - admin
    ports:
      - 8000:8000
    volumes:
      - ./../apps/sync:/apps/sync
      - ./../config.yml:/apps/sync/config.yml
    depends_on:
      wywywebsite-cache_database:
        condition: service_healthy

  # @TODO secrets for db authentication
  wywywebsite-cache_database:
    container_name: wywywebsite-cache_postgres
    image: postgres
    working_dir: /apps/postgres
    restart: always
    env_file:
      - path: .env
        required: true
      - path: .env.dev
        required: true
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${DATABASE_USERNAME}",
          "-p",
          "${DATABASE_PORT}",
        ]
      interval: 5m
      timeout: 5s
      start_period: 3s
      retries: 10
    volumes:
      # - postgres-db:/var/lib/postgresql
      - ./../apps/postgres:/var/lib/postgresql
    shm_size: 128mb
    command: -p ${DATABASE_PORT}

secrets:
  admin:
    file: ./../secrets/admin.txt
